# Generated by Django 5.0.3 on 2024-03-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_customuser_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='customuser_id',
            new_name='id',
        ),
    ]
