# Generated by Django 5.0.3 on 2024-03-23 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name_encrypted', models.BinaryField()),
                ('branch_encrypted', models.BinaryField()),
                ('address_encrypted', models.BinaryField(blank=True, null=True)),
                ('established_date_encrypted', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks_created', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks_updated', to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
        ),
    ]
