# Generated by Django 5.0.3 on 2024-03-23 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_alter_bank_address_encrypted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='address_encrypted',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='bank_name_encrypted',
            new_name='bank_name',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='branch_encrypted',
            new_name='branch',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='established_date_encrypted',
        ),
        migrations.AddField(
            model_name='bank',
            name='established_date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_created', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_updated', to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('yearly_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='Employee.bank')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.bank')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_created', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('employee_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_emails', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_updated', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.role')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries_created', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.employee')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries_updated', to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
        ),
    ]
